name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build jar
        run: |
          mvn package
      - name: Build native image
        run: |
          native-image -jar target/local-lang.jar

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: local-lang-${{ matrix.os }}
          path: local-lang*